/**
 * Parent-Version Migration Fixture Test — v57 → v58 (weighed goods)
 *
 * Usage: node tests/run-electron-node-test.cjs tests/migration-v57-to-v58.test.ts
 *
 * Migration v58 adds the unit-of-measure and scale-label columns that turn
 * this till into a supermarket one. It is additive by design: no table is
 * rebuilt, and in particular order_items keeps its INTEGER-declared quantity
 * column (SQLite's INTEGER affinity stores a weighed 0.734 as REAL without
 * loss). Both of those claims are asserted here against a REAL frozen v57
 * install rather than a synthetic schema, because the risk this test exists
 * to catch is precisely the one a fresh-install check cannot see: a migration
 * that conflicts with the shape of the database immediately before it.
 *
 * The fixture is tests/fixtures/upgrade-snapshots/schema-v57-pre-weighed-goods.db,
 * generated by scripts/generate-upgrade-fixture.ts (see that file's header).
 * It is seeded below with the kind of history a real shop would already have —
 * products and paid order lines — so the test can prove that history survives
 * intact and is backfilled with the right defaults.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-migration-v57-v58-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/schema-v57-pre-weighed-goods.db');
const dbPath = path.join(testDir, 'flo.db');
fs.copyFileSync(FIXTURE, dbPath);

// ── Seed the fixture with a real pre-migration shop ────────────────────────
const FixtureDatabase = require('better-sqlite3');
const fixtureDb = new FixtureDatabase(dbPath);
assert.equal(fixtureDb.pragma('user_version', { simple: true }), 57, 'fixture is frozen at schema v57');

// A v57 install cannot know about unit_of_measure — assert that, so this test
// fails loudly if the fixture is ever regenerated from a build that already
// has v58 (which would make every assertion below vacuous).
const v57ProductCols = (fixtureDb.prepare('PRAGMA table_info(products)').all() as { name: string }[]).map((c) => c.name);
assert.ok(!v57ProductCols.includes('unit_of_measure'), 'fixture predates the v58 columns');

fixtureDb.prepare(`
  INSERT INTO products (id, name, price, barcode, is_active, created_at, updated_at)
  VALUES (?, ?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`).run('prod-thon', 'Thon a l huile', 8.5, '6111234567892');
fixtureDb.prepare(`
  INSERT INTO products (id, name, price, is_active, created_at, updated_at)
  VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`).run('prod-lentilles', 'Lentilles vrac', 12.5);

fixtureDb.prepare(`INSERT INTO orders (order_number, status, subtotal, total) VALUES (?, ?, ?, ?)`)
  .run('ORD-LEGACY-1', 'completed', 17, 17);
const legacyOrderId = (fixtureDb.prepare(`SELECT id FROM orders WHERE order_number = 'ORD-LEGACY-1'`)
  .get() as { id: number }).id;
fixtureDb.prepare(`
  INSERT INTO order_items (order_id, product_id, product_name, unit_price, quantity, subtotal, total)
  VALUES (?, ?, ?, ?, ?, ?, ?)
`).run(legacyOrderId, 'prod-thon', 'Thon a l huile', 8.5, 2, 17, 17);
fixtureDb.close();

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};
Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function columnsOf(db: any, table: string): Map<string, { type: string; notnull: number; dflt_value: string | null }> {
  const rows = db.prepare(`PRAGMA table_info(${table})`).all() as
    { name: string; type: string; notnull: number; dflt_value: string | null }[];
  return new Map(rows.map((r) => [r.name, { type: r.type, notnull: r.notnull, dflt_value: r.dflt_value }]));
}

function main() {
  console.log('🧪 Migration v57 → v58 Parent-Version Fixture Test (weighed goods)');
  console.log('='.repeat(60));

  const { initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb } = require('../main/db');

  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real v57 install crashed: ${error.message}`);
  }

  const db = getDatabase();
  const ideal = buildIdealSchemaDb();
  const latestSchemaVersion = ideal.pragma('user_version', { simple: true }) as number;
  ideal.close();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion,
    'a real v57 install reaches the same schema version as a fresh install');
  console.log(`   ✓ v57 fixture migrates cleanly to v${latestSchemaVersion}`);

  // ── The new columns exist, with the defaults the API relies on ──────────
  const productCols = columnsOf(db, 'products');
  for (const [name, type, notnull, dflt] of [
    ['unit_of_measure', 'TEXT', 1, `'unit'`],
    ['quantity_precision', 'INTEGER', 1, '0'],
    ['plu_code', 'TEXT', 0, null],
    ['tare_default', 'REAL', 1, '0'],
    ['max_quantity', 'REAL', 0, null],
  ] as [string, string, number, string | null][]) {
    const col = productCols.get(name);
    assert.ok(col, `products.${name} exists after v58`);
    assert.equal(col!.type, type, `products.${name} is ${type}`);
    assert.equal(col!.notnull, notnull, `products.${name} notnull flag`);
    assert.equal(col!.dflt_value, dflt, `products.${name} default`);
  }

  const itemCols = columnsOf(db, 'order_items');
  for (const [name, dflt] of [
    ['unit_of_measure', `'unit'`],
    ['quantity_source', `'unit'`],
    ['amount_source', `'computed'`],
    ['scan_raw', null],
  ] as [string, string | null][]) {
    const col = itemCols.get(name);
    assert.ok(col, `order_items.${name} exists after v58`);
    assert.equal(col!.dflt_value, dflt, `order_items.${name} default`);
  }
  console.log('   ✓ all nine v58 columns land with the expected types and defaults');

  // ── order_items was NOT rebuilt ────────────────────────────────────────
  // A rebuild would have had to re-list this table's live columns, which are
  // createSchema's list MINUS `addons` (dropped by v30) PLUS `voided_at`
  // (added by v34). Asserting both survive is what catches a future rebuild.
  assert.ok(itemCols.has('voided_at'), 'order_items.voided_at survives (would be lost by a naive rebuild)');
  assert.ok(!itemCols.has('addons'), 'order_items.addons stays dropped (a naive rebuild would resurrect or crash on it)');
  assert.equal(itemCols.get('quantity')!.type, 'INTEGER',
    'order_items.quantity keeps its INTEGER declaration — deliberately, see the lock comment in db.ts');
  console.log('   ✓ order_items was extended, not rebuilt');

  // ── Pre-existing history is intact and correctly backfilled ────────────
  const legacyItem = db.prepare(`
    SELECT quantity, subtotal, total, unit_of_measure, quantity_source, amount_source, scan_raw
    FROM order_items WHERE product_id = 'prod-thon'
  `).get() as any;
  assert.equal(legacyItem.quantity, 2, 'a pre-existing line keeps its quantity');
  assert.equal(legacyItem.subtotal, 17, 'a pre-existing line keeps its money');
  assert.equal(legacyItem.unit_of_measure, 'unit', 'a pre-existing line is backfilled as countable');
  assert.equal(legacyItem.quantity_source, 'unit', 'a pre-existing line is backfilled as unit-sourced');
  assert.equal(legacyItem.amount_source, 'computed', 'a pre-existing line is backfilled as computed');
  assert.equal(legacyItem.scan_raw, null, 'a pre-existing line has no scan payload');

  const legacyProduct = db.prepare(`SELECT price, barcode, unit_of_measure, plu_code FROM products WHERE id = 'prod-thon'`).get() as any;
  assert.equal(legacyProduct.price, 8.5, 'a pre-existing product keeps its price');
  assert.equal(legacyProduct.barcode, '6111234567892', 'a pre-existing product keeps its GTIN');
  assert.equal(legacyProduct.unit_of_measure, 'unit', 'a pre-existing product defaults to countable');
  assert.equal(legacyProduct.plu_code, null, 'a pre-existing product has no scale item code');
  console.log('   ✓ pre-existing products and sold lines survive with correct backfill');

  // ── The point of the whole migration: a weighed line round-trips ────────
  db.prepare(`UPDATE products SET unit_of_measure = 'kg', quantity_precision = 3, plu_code = '02001' WHERE id = 'prod-lentilles'`).run();
  db.prepare(`INSERT INTO orders (order_number, status) VALUES ('ORD-WEIGHED-1', 'pending')`).run();
  const weighedOrderId = (db.prepare(`SELECT id FROM orders WHERE order_number = 'ORD-WEIGHED-1'`).get() as { id: number }).id;
  db.prepare(`
    INSERT INTO order_items (order_id, product_id, product_name, unit_price, quantity, subtotal, total,
                             unit_of_measure, quantity_source, scan_raw)
    VALUES (?, ?, ?, ?, ?, ?, ?, 'kg', 'scale_label', ?)
  `).run(weighedOrderId, 'prod-lentilles', 'Lentilles vrac', 12.5, 0.734, 9.18, 9.18, '2020010007347');

  const weighed = db.prepare(`
    SELECT quantity, typeof(quantity) AS qtype, unit_of_measure, quantity_source, scan_raw, total
    FROM order_items WHERE order_id = ?
  `).get(weighedOrderId) as any;
  assert.equal(weighed.quantity, 0.734, '0.734 kg is stored without loss in an INTEGER-declared column');
  assert.equal(weighed.qtype, 'real', 'SQLite keeps it as REAL — INTEGER affinity only converts losslessly');
  assert.equal(weighed.unit_of_measure, 'kg', 'the line records how it was measured');
  assert.equal(weighed.quantity_source, 'scale_label', 'the line records where the quantity came from');
  assert.equal(weighed.scan_raw, '2020010007347', 'the raw scan is kept for audit');

  const summed = db.prepare(`SELECT SUM(quantity) AS s FROM order_items WHERE order_id = ?`).get(weighedOrderId) as any;
  assert.equal(summed.s, 0.734, 'SUM() over a weighed quantity stays exact');
  console.log('   ✓ a weighed sale round-trips exactly through the migrated schema');

  // ── PLU uniqueness is enforced by the database, not by the API ──────────
  assert.throws(
    () => db.prepare(`INSERT INTO products (id, name, price, plu_code) VALUES ('dup', 'Riz vrac', 9.9, '02001')`).run(),
    /UNIQUE constraint failed/,
    'a duplicate scale item code is rejected by the index, not merely by a SELECT in the API',
  );
  // Partial index: the many products with no PLU must still coexist freely.
  db.prepare(`INSERT INTO products (id, name, price) VALUES ('no-plu-a', 'Sardines', 7)`).run();
  db.prepare(`INSERT INTO products (id, name, price) VALUES ('no-plu-b', 'Farine 1kg', 11)`).run();
  console.log('   ✓ PLU uniqueness enforced in SQL, and products without a PLU are unaffected');

  // ── Scale decoding ships disabled ──────────────────────────────────────
  const enabled = db.prepare(`SELECT value FROM settings WHERE key = 'scale_labels_enabled'`).get() as any;
  assert.equal(enabled?.value, 'false',
    'label decoding is seeded OFF: a mis-configured label format bills a wrong weight while keeping a valid check digit');
  const format = db.prepare(`SELECT value FROM settings WHERE key = 'scale_label_format'`).get() as any;
  assert.doesNotThrow(() => JSON.parse(format.value), 'the seeded label format is valid JSON');
  console.log('   ✓ scale-label decoding is seeded disabled, with a parseable default format');

  closeDatabase();

  // ── The migration is re-runnable ───────────────────────────────────────
  // upgrade-path.test.ts rewinds user_version and replays the tail of the
  // chain over an already-migrated database, so every statement in v58 must
  // tolerate its own output. Prove it directly rather than by implication.
  const rewind = new FixtureDatabase(dbPath);
  rewind.pragma('user_version = 57');
  rewind.close();
  assert.doesNotThrow(() => initDatabase(), 'v58 replays cleanly over a database it has already migrated');
  const replayed = getDatabase();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion, 'the replay lands on the same version');
  const survivor = replayed.prepare(`SELECT quantity, unit_of_measure FROM order_items WHERE product_id = 'prod-lentilles'`).get() as any;
  assert.equal(survivor.quantity, 0.734, 'the replay does not disturb existing weighed data');
  assert.equal(survivor.unit_of_measure, 'kg', 'the replay does not reset a line to its column default');
  closeDatabase();
  console.log('   ✓ v58 is idempotent: replaying it over its own output changes nothing');

  console.log('='.repeat(60));
  console.log('✅ Migration v57 → v58 fixture test passed');
}

main();
