#!/usr/bin/env python3
"""
Generate main/printers/arabic-tables.ts from the Unicode character database.

    python3 scripts/gen-arabic-tables.py > main/printers/arabic-tables.ts

Three tables come out of this, none of which should be typed by hand:

  FORMS       every Arabic letter's isolated / final / initial / medial glyph,
              read from the decompositions of the presentation-forms block
  LIGATURES   the lam-alef pairs, which must become one glyph
  CP864/1256  Unicode to byte, for the two Arabic code pages an ESC/POS
              printer might be set to

The joining class of a letter is not stored separately: a letter that has no
initial and no medial form is one that only joins to its right (alef, dal, ra,
waw...), which is exactly what the shaping pass needs to know.
"""
import unicodedata

ISO, FIN, INI, MED = 0, 1, 2, 3
KEY = {'<isolated>': ISO, '<final>': FIN, '<initial>': INI, '<medial>': MED}


def main() -> None:
    forms, ligatures = {}, {}
    for cp in range(0xFE70, 0xFEFD):
        ch = chr(cp)
        dec = unicodedata.decomposition(ch)
        if not dec:
            continue
        tag, *codes = dec.split()
        if tag not in KEY:
            continue
        base = ''.join(chr(int(c, 16)) for c in codes)
        target = ligatures if len(base) > 1 else forms
        target.setdefault(base, [None, None, None, None])[KEY[tag]] = ch

    def esc(s: str) -> str:
        return ''.join(f'\\u{ord(c):04X}' for c in s)

    print("// GENERATED by scripts/gen-arabic-tables.py — do not edit by hand.")
    print("// Source: the Unicode character database's decompositions for the")
    print("// Arabic presentation-forms block (U+FE70..U+FEFC).")
    print()
    print("/** Base letter -> [isolated, final, initial, medial]. */")
    print("export const FORMS: Record<string, (string | null)[]> = {")
    for base, f in sorted(forms.items()):
        cells = ', '.join('null' if x is None else f"'{esc(x)}'" for x in f)
        print(f"  '{esc(base)}': [{cells}],")
    print("};")
    print()
    print("/** Lam-alef pairs: two letters that must print as a single glyph. */")
    print("export const LIGATURES: Record<string, (string | null)[]> = {")
    for base, f in sorted(ligatures.items()):
        cells = ', '.join('null' if x is None else f"'{esc(x)}'" for x in f)
        print(f"  '{esc(base)}': [{cells}],")
    print("};")
    for cp in ('cp864', 'cp1256'):
        mapping = {}
        for b in range(256):
            try:
                mapping[bytes([b]).decode(cp)] = b
            except Exception:
                pass
        print()
        print(f"/** Unicode -> byte, {cp.upper()} code page. ASCII is omitted: it maps to itself. */")
        print(f"export const {cp.upper()}: Record<string, number> = {{")
        for ch, b in sorted(mapping.items(), key=lambda x: x[1]):
            if ord(ch) < 0x80 and ch == chr(b):
                continue
            print(f"  '{esc(ch)}': 0x{b:02X},")
        print("};")


if __name__ == '__main__':
    main()
